from BaseClasses import ItemClassification
from .keys import ItemKey

item_table = {
    # ----------- KEY ----------------------------- ITEM NAME ----------------------------------------------------- CLASSIFICATION ---------------------- #
    ItemKey.NONE:                               ("No Item",                                     ItemClassification.filler),
    ItemKey.KOKIRI_SWORD:                       ("Kokiri Sword",                                ItemClassification.progression | ItemClassification.useful),
    ItemKey.MASTER_SWORD:                       ("Master Sword",                                ItemClassification.progression | ItemClassification.useful),
    ItemKey.GIANTS_KNIFE:                       ("Giant's Knife",                               ItemClassification.progression | ItemClassification.useful),
    ItemKey.BIGGORON_SWORD:                     ("Biggoron Sword",                              ItemClassification.progression | ItemClassification.useful),
    ItemKey.DEKU_SHIELD:                        ("Deku Shield",                                 ItemClassification.progression_deprioritized_skip_balancing),
    ItemKey.HYLIAN_SHIELD:                      ("Hylian Shield",                               ItemClassification.progression_deprioritized_skip_balancing),
    ItemKey.MIRROR_SHIELD:                      ("Mirror Shield",                               ItemClassification.progression | ItemClassification.useful),
    ItemKey.GORON_TUNIC:                        ("Goron Tunic",                                 ItemClassification.progression | ItemClassification.useful),
    ItemKey.ZORA_TUNIC:                         ("Zora Tunic",                                  ItemClassification.progression | ItemClassification.useful),
    ItemKey.IRON_BOOTS:                         ("Iron Boots",                                  ItemClassification.progression | ItemClassification.useful),

    ItemKey.HOVER_BOOTS:                        ("Hover Boots",                                 ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOOMERANG:                          ("Boomerang",                                   ItemClassification.progression | ItemClassification.useful),
    ItemKey.LENS_OF_TRUTH:                      ("Lens of Truth",                               ItemClassification.progression | ItemClassification.useful),
    ItemKey.MEGATON_HAMMER:                     ("Megaton Hammer",                              ItemClassification.progression | ItemClassification.useful),
    ItemKey.SHARD_OF_AGONY:                     ("Shard of Agony",                              ItemClassification.progression_deprioritized_skip_balancing),
    ItemKey.DINS_FIRE:                          ("Din's Fire",                                  ItemClassification.progression | ItemClassification.useful),
    ItemKey.FARORES_WIND:                       ("Farore's Wind",                               ItemClassification.progression | ItemClassification.useful),
    ItemKey.NAYRUS_LOVE:                        ("Nayru's Love",                                ItemClassification.progression | ItemClassification.useful),
    ItemKey.FIRE_ARROWS:                        ("Fire Arrows",                                 ItemClassification.progression | ItemClassification.useful),
    ItemKey.ICE_ARROWS:                         ("Ice Arrows",                                  ItemClassification.progression | ItemClassification.useful),
    ItemKey.LIGHT_ARROWS:                       ("Light Arrows",                                ItemClassification.progression | ItemClassification.useful),
    ItemKey.GERUDO_TOKEN:                       ("Gerudo Token",                                ItemClassification.progression | ItemClassification.useful),
    ItemKey.MAGIC_BEAN:                         ("Magic Bean",                                  ItemClassification.progression),
    ItemKey.MAGIC_BEAN_PACK:                    ("Magic Bean Pack",                             ItemClassification.progression),
    ItemKey.DOUBLE_DEFENSE:                     ("Double Defense",                              ItemClassification.progression | ItemClassification.useful),

    ItemKey.WEIRD_EGG:                          ("Weird Egg",                                   ItemClassification.progression),
    ItemKey.ZELDAS_LETTER:                      ("Zelda's Letter",                              ItemClassification.progression),
    ItemKey.POCKET_EGG:                         ("Pocket Egg",                                  ItemClassification.progression_deprioritized_skip_balancing),
    ItemKey.COJIRO:                             ("Cojiro",                                      ItemClassification.progression_deprioritized_skip_balancing),
    ItemKey.ODD_MUSHROOM:                       ("Odd Mushroom",                                ItemClassification.progression_deprioritized_skip_balancing),
    ItemKey.ODD_POULTICE:                       ("Odd Poultice",                                ItemClassification.progression_deprioritized_skip_balancing),
    ItemKey.POACHERS_SAW:                       ("Poacher's Saw",                               ItemClassification.progression_deprioritized_skip_balancing),
    ItemKey.BROKEN_SWORD:                       ("Broken Sword",                                ItemClassification.progression_deprioritized_skip_balancing),
    ItemKey.PRESCRIPTION:                       ("Prescription",                                ItemClassification.progression_deprioritized_skip_balancing),
    ItemKey.EYEBALL_FROG:                       ("Eyeball Frog",                                ItemClassification.progression_deprioritized_skip_balancing),
    ItemKey.EYEDROPS:                           ("Eyedrops",                                    ItemClassification.progression_deprioritized_skip_balancing),
    ItemKey.CLAIM_CHECK:                        ("Claim Check",                                 ItemClassification.progression_deprioritized_skip_balancing),

    ItemKey.GOLD_SKULLTULA_TOKEN:               ("Gold Skulltula Token",                        ItemClassification.progression_deprioritized_skip_balancing),

    # Progressive Items
    ItemKey.PROGRESSIVE_HOOKSHOT:               ("Progressive Hookshot",                        ItemClassification.progression | ItemClassification.useful),
    ItemKey.PROGRESSIVE_STRENGTH:               ("Progressive Strength",                        ItemClassification.progression | ItemClassification.useful),
    ItemKey.PROGRESSIVE_BOMB_BAG:               ("Progressive Bomb Bag",                        ItemClassification.progression | ItemClassification.useful),
    ItemKey.PROGRESSIVE_BOW:                    ("Progressive Bow",                             ItemClassification.progression | ItemClassification.useful),
    ItemKey.PROGRESSIVE_SLINGSHOT:              ("Progressive Slingshot",                       ItemClassification.progression | ItemClassification.useful),
    ItemKey.PROGRESSIVE_WALLET:                 ("Progressive Wallet",                          ItemClassification.progression | ItemClassification.useful),
    ItemKey.PROGRESSIVE_SCALE:                  ("Progressive Scale",                           ItemClassification.progression | ItemClassification.useful),
    ItemKey.PROGRESSIVE_NUT_UPGRADE:            ("Progressive Nut Upgrade",                     ItemClassification.useful),
    ItemKey.PROGRESSIVE_STICK_UPGRADE:          ("Progressive Stick Upgrade",                   ItemClassification.useful),
    ItemKey.PROGRESSIVE_BOMBCHUS:               ("Progressive Bombchus",                        ItemClassification.progression | ItemClassification.useful),
    ItemKey.PROGRESSIVE_MAGIC_METER:            ("Progressive Magic Meter",                     ItemClassification.progression | ItemClassification.useful),
    ItemKey.PROGRESSIVE_OCARINA:                ("Progressive Ocarina",                         ItemClassification.progression | ItemClassification.useful),
    ItemKey.PROGRESSIVE_GORONSWORD:             ("Progressive Goron Sword",                     ItemClassification.progression | ItemClassification.useful),

    # Bottles
    ItemKey.EMPTY_BOTTLE:                       ("Empty Bottle",                                ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOTTLE_WITH_RED_POTION:             ("Bottle with Red Potion",                      ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOTTLE_WITH_MILK:                   ("Bottle with Milk",                            ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOTTLE_WITH_GREEN_POTION:           ("Bottle with Green Potion",                    ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOTTLE_WITH_BLUE_POTION:            ("Bottle with Blue Potion",                     ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOTTLE_WITH_FAIRY:                  ("Bottle with Fairy",                           ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOTTLE_WITH_FISH:                   ("Bottle with Fish",                            ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOTTLE_WITH_BLUE_FIRE:              ("Bottle with Blue Fire",                       ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOTTLE_WITH_BUGS:                   ("Bottle with Bugs",                            ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOTTLE_WITH_POE:                    ("Bottle with Poe",                             ItemClassification.progression | ItemClassification.useful),

    # Special bottles that can't immediately dump contents
    ItemKey.RUTOS_LETTER:                       ("Bottle with Ruto's Letter",                   ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOTTLE_WITH_BIG_POE:                ("Bottle with Big Poe",                         ItemClassification.progression | ItemClassification.useful),

    # Songs
    ItemKey.ZELDAS_LULLABY:                     ("Zelda's Lullaby",                             ItemClassification.progression | ItemClassification.useful),
    ItemKey.EPONAS_SONG:                        ("Epona's Song",                                ItemClassification.progression | ItemClassification.useful),
    ItemKey.SARIAS_SONG:                        ("Saria's Song",                                ItemClassification.progression | ItemClassification.useful),
    ItemKey.SUNS_SONG:                          ("Sun's Song",                                  ItemClassification.progression | ItemClassification.useful),
    ItemKey.SONG_OF_TIME:                       ("Song of Time",                                ItemClassification.progression | ItemClassification.useful),
    ItemKey.SONG_OF_STORMS:                     ("Song of Storms",                              ItemClassification.progression | ItemClassification.useful),
    ItemKey.MINUET_OF_FOREST:                   ("Minuet of Forest",                            ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOLERO_OF_FIRE:                     ("Bolero of Fire",                              ItemClassification.progression | ItemClassification.useful),
    ItemKey.SERENADE_OF_WATER:                  ("Serenade of Water",                           ItemClassification.progression | ItemClassification.useful),
    ItemKey.REQUIEM_OF_SPIRIT:                  ("Requiem of Spirit",                           ItemClassification.progression | ItemClassification.useful),
    ItemKey.NOCTURNE_OF_SHADOW:                 ("Nocturne of Shadow",                          ItemClassification.progression | ItemClassification.useful),
    ItemKey.PRELUDE_OF_LIGHT:                   ("Prelude of Light",                            ItemClassification.progression | ItemClassification.useful),

    # Maps and Compasses
    ItemKey.DEKU_TREE_MAP:                      ("Great Deku Tree Map",                         ItemClassification.useful),
    ItemKey.DODONGOS_CAVERN_MAP:                ("Dodongo's Cavern Map",                        ItemClassification.useful),
    ItemKey.JABU_JABUS_BELLY_MAP:               ("Jabu-Jabu's Belly Map",                       ItemClassification.useful),
    ItemKey.FOREST_TEMPLE_MAP:                  ("Forest Temple Map",                           ItemClassification.useful),
    ItemKey.FIRE_TEMPLE_MAP:                    ("Fire Temple Map",                             ItemClassification.useful),
    ItemKey.WATER_TEMPLE_MAP:                   ("Water Temple Map",                            ItemClassification.useful),
    ItemKey.SPIRIT_TEMPLE_MAP:                  ("Spirit Temple Map",                           ItemClassification.useful),
    ItemKey.SHADOW_TEMPLE_MAP:                  ("Shadow Temple Map",                           ItemClassification.useful),
    ItemKey.BOTTOM_OF_THE_WELL_MAP:             ("Bottom of the Well Map",                      ItemClassification.useful),
    ItemKey.ICE_CAVERN_MAP:                     ("Ice Cavern Map",                              ItemClassification.useful),

    ItemKey.DEKU_TREE_COMPASS:                  ("Great Deku Tree Compass",                     ItemClassification.useful),
    ItemKey.DODONGOS_CAVERN_COMPASS:            ("Dodongo's Cavern Compass",                    ItemClassification.useful),
    ItemKey.JABU_JABUS_BELLY_COMPASS:           ("Jabu-Jabu's Belly Compass",                   ItemClassification.useful),
    ItemKey.FOREST_TEMPLE_COMPASS:              ("Forest Temple Compass",                       ItemClassification.useful),
    ItemKey.FIRE_TEMPLE_COMPASS:                ("Fire Temple Compass",                         ItemClassification.useful),
    ItemKey.WATER_TEMPLE_COMPASS:               ("Water Temple Compass",                        ItemClassification.useful),
    ItemKey.SPIRIT_TEMPLE_COMPASS:              ("Spirit Temple Compass",                       ItemClassification.useful),
    ItemKey.SHADOW_TEMPLE_COMPASS:              ("Shadow Temple Compass",                       ItemClassification.useful),
    ItemKey.BOTTOM_OF_THE_WELL_COMPASS:         ("Bottom of the Well Compass",                  ItemClassification.useful),
    ItemKey.ICE_CAVERN_COMPASS:                 ("Ice Cavern Compass",                          ItemClassification.useful),

    # Boss Keys
    ItemKey.FOREST_TEMPLE_BOSS_KEY:             ("Forest Temple Boss Key",                      ItemClassification.progression),
    ItemKey.FIRE_TEMPLE_BOSS_KEY:               ("Fire Temple Boss Key",                        ItemClassification.progression),
    ItemKey.WATER_TEMPLE_BOSS_KEY:              ("Water Temple Boss Key",                       ItemClassification.progression),
    ItemKey.SPIRIT_TEMPLE_BOSS_KEY:             ("Spirit Temple Boss Key",                      ItemClassification.progression),
    ItemKey.SHADOW_TEMPLE_BOSS_KEY:             ("Shadow Temple Boss Key",                      ItemClassification.progression),
    ItemKey.GANONS_CASTLE_BOSS_KEY:             ("Ganon's Castle Boss Key",                     ItemClassification.progression),

    # Small Keys
    ItemKey.FOREST_TEMPLE_SMALL_KEY:            ("Forest Temple Small Key",                     ItemClassification.progression),
    ItemKey.FIRE_TEMPLE_SMALL_KEY:              ("Fire Temple Small Key",                       ItemClassification.progression),
    ItemKey.WATER_TEMPLE_SMALL_KEY:             ("Water Temple Small Key",                      ItemClassification.progression),
    ItemKey.SPIRIT_TEMPLE_SMALL_KEY:            ("Spirit Temple Small Key",                     ItemClassification.progression),
    ItemKey.SHADOW_TEMPLE_SMALL_KEY:            ("Shadow Temple Small Key",                     ItemClassification.progression),
    ItemKey.BOTTOM_OF_THE_WELL_SMALL_KEY:       ("Bottom of the Well Small Key",                ItemClassification.progression),
    ItemKey.GERUDO_TRAINING_GROUNDS_SMALL_KEY:  ("Gerudo Training Grounds Small Key",           ItemClassification.progression),
    ItemKey.GERUDO_FORTRESS_SMALL_KEY:          ("Gerudo Fortress Small Key",                   ItemClassification.progression),
    ItemKey.GANONS_CASTLE_SMALL_KEY:            ("Ganon's Castle Small Key",                    ItemClassification.progression),
    ItemKey.TREASURE_GAME_SMALL_KEY:            ("Treasure Game Small Key",                     ItemClassification.progression),

    # Key Rings
    ItemKey.FOREST_TEMPLE_KEY_RING:             ("Forest Temple Key Ring",                      ItemClassification.progression),
    ItemKey.FIRE_TEMPLE_KEY_RING:               ("Fire Temple Key Ring",                        ItemClassification.progression),
    ItemKey.WATER_TEMPLE_KEY_RING:              ("Water Temple Key Ring",                       ItemClassification.progression),
    ItemKey.SPIRIT_TEMPLE_KEY_RING:             ("Spirit Temple Key Ring",                      ItemClassification.progression),
    ItemKey.SHADOW_TEMPLE_KEY_RING:             ("Shadow Temple Key Ring",                      ItemClassification.progression),
    ItemKey.BOTTOM_OF_THE_WELL_KEY_RING:        ("Bottom of the Well Key Ring",                 ItemClassification.progression),
    ItemKey.GERUDO_TRAINING_GROUNDS_KEY_RING:   ("Gerudo Training Grounds Key Ring",            ItemClassification.progression),
    ItemKey.GERUDO_FORTRESS_KEY_RING:           ("Gerudo Fortress Key Ring",                    ItemClassification.progression),
    ItemKey.GANONS_CASTLE_KEY_RING:             ("Ganon's Castle Key Ring",                     ItemClassification.progression),

    # Stones and Medallions
    ItemKey.KOKIRI_EMERALD:                     ("Kokiri's Emerald",                            ItemClassification.progression_skip_balancing),
    ItemKey.GORON_RUBY:                         ("Goron's Ruby",                                ItemClassification.progression_skip_balancing),
    ItemKey.ZORA_SAPPHIRE:                      ("Zora's Sapphire",                             ItemClassification.progression_skip_balancing),
    ItemKey.FOREST_MEDALLION:                   ("Forest Medallion",                            ItemClassification.progression_skip_balancing),
    ItemKey.FIRE_MEDALLION:                     ("Fire Medallion",                              ItemClassification.progression_skip_balancing),
    ItemKey.WATER_MEDALLION:                    ("Water Medallion",                             ItemClassification.progression_skip_balancing),
    ItemKey.SPIRIT_MEDALLION:                   ("Spirit Medallion",                            ItemClassification.progression_skip_balancing),
    ItemKey.SHADOW_MEDALLION:                   ("Shadow Medallion",                            ItemClassification.progression_skip_balancing),
    ItemKey.LIGHT_MEDALLION:                    ("Light Medallion",                             ItemClassification.progression_skip_balancing),

    # Generic Items
    ItemKey.RECOVERY_HEART:                     ("Recovery Heart",                              ItemClassification.filler),
    ItemKey.GREEN_RUPEE:                        ("Green Rupee",                                 ItemClassification.filler),
    ItemKey.BLUE_RUPEE:                         ("Blue Rupee",                                  ItemClassification.filler),
    ItemKey.RED_RUPEE:                          ("Red Rupee",                                   ItemClassification.filler),
    ItemKey.PURPLE_RUPEE:                       ("Purple Rupee",                                ItemClassification.filler),
    ItemKey.HUGE_RUPEE:                         ("Huge Rupee",                                  ItemClassification.filler),
    ItemKey.PIECE_OF_HEART:                     ("Piece of Heart",                              ItemClassification.progression | ItemClassification.useful),
    ItemKey.HEART_CONTAINER:                    ("Heart Container",                             ItemClassification.progression | ItemClassification.useful),
    ItemKey.ICE_TRAP:                           ("Ice Trap",                                    ItemClassification.trap),
    ItemKey.MILK:                               ("Milk",                                        ItemClassification.filler),

    # Refills
    ItemKey.BOMBS_5:                            ("Bombs (5)",                                   ItemClassification.filler),
    ItemKey.BOMBS_10:                           ("Bombs (10)",                                  ItemClassification.filler),
    ItemKey.BOMBS_20:                           ("Bombs (20)",                                  ItemClassification.filler),
    ItemKey.BOMBCHU_5:                          ("Bombchu (5)",                                 ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOMBCHU_10:                         ("Bombchu (10)",                                ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOMBCHU_20:                         ("Bombchu (20)",                                ItemClassification.progression | ItemClassification.useful),
    ItemKey.BOMBCHU_DROP:                       ("Bombchu Drop",                                ItemClassification.progression | ItemClassification.useful),
    ItemKey.ARROWS_5:                           ("Arrows (5)",                                  ItemClassification.filler),
    ItemKey.ARROWS_10:                          ("Arrows (10)",                                 ItemClassification.filler),
    ItemKey.ARROWS_30:                          ("Arrows (30)",                                 ItemClassification.filler),
    ItemKey.DEKU_NUTS_5:                        ("Deku Nuts (5)",                               ItemClassification.filler),
    ItemKey.DEKU_NUTS_10:                       ("Deku Nuts (10)",                              ItemClassification.filler),
    ItemKey.DEKU_SEEDS_30:                      ("Deku Seeds (30)",                             ItemClassification.filler),
    ItemKey.DEKU_STICK_1:                       ("Deku Stick (1)",                              ItemClassification.filler),
    ItemKey.RED_POTION_REFILL:                  ("Red Potion Refill",                           ItemClassification.filler),
    ItemKey.GREEN_POTION_REFILL:                ("Green Potion Refill",                         ItemClassification.filler),
    ItemKey.BLUE_POTION_REFILL:                 ("Blue Potion Refill",                          ItemClassification.filler),

    # Treasure Game
    ItemKey.TREASURE_GAME_HEART:                ("Piece of Heart (Treasure Chest Minigame)",    ItemClassification.progression | ItemClassification.useful),
    ItemKey.TREASURE_GAME_GREEN_RUPEE:          ("Green Rupee (Treasure Chest Minigame)",       ItemClassification.filler),

    # Shop Items
    ItemKey.BUY_DEKU_NUT_5:                     ("Buy Deku Nut (5)",                            ItemClassification.progression),
    ItemKey.BUY_ARROWS_30:                      ("Buy Arrows (30)",                             ItemClassification.progression),
    ItemKey.BUY_ARROWS_50:                      ("Buy Arrows (50)",                             ItemClassification.progression),
    ItemKey.BUY_BOMBS_525:                      ("Buy Bombs (5) [25]",                          ItemClassification.progression),
    ItemKey.BUY_DEKU_NUT_10:                    ("Buy Deku Nut (10)",                           ItemClassification.progression),
    ItemKey.BUY_DEKU_STICK_1:                   ("Buy Deku Stick (1)",                          ItemClassification.progression),
    ItemKey.BUY_BOMBS_10:                       ("Buy Bombs (10)",                              ItemClassification.progression),
    ItemKey.BUY_FISH:                           ("Buy Fish",                                    ItemClassification.progression),
    ItemKey.BUY_RED_POTION_30:                  ("Buy Red Potion [30]",                         ItemClassification.filler),
    ItemKey.BUY_GREEN_POTION:                   ("Buy Green Potion",                            ItemClassification.progression),
    ItemKey.BUY_BLUE_POTION:                    ("Buy Blue Potion",                             ItemClassification.progression),
    ItemKey.BUY_HYLIAN_SHIELD:                  ("Buy Hylian Shield",                           ItemClassification.progression),
    ItemKey.BUY_DEKU_SHIELD:                    ("Buy Deku Shield",                             ItemClassification.progression),
    ItemKey.BUY_GORON_TUNIC:                    ("Buy Goron Tunic",                             ItemClassification.progression),
    ItemKey.BUY_ZORA_TUNIC:                     ("Buy Zora Tunic",                              ItemClassification.progression),
    ItemKey.BUY_HEART:                          ("Buy Heart",                                   ItemClassification.filler),
    ItemKey.BUY_BOMBCHU_10:                     ("Buy Bombchu (10)",                            ItemClassification.progression),
    ItemKey.BUY_BOMBCHU_20:                     ("Buy Bombchu (20)",                            ItemClassification.progression),
    ItemKey.BUY_BOMBCHU_5:                      ("Buy Bombchu (5)",                             ItemClassification.progression),
    ItemKey.BUY_DEKU_SEEDS_30:                  ("Buy Deku Seeds (30)",                         ItemClassification.progression),
    ItemKey.SOLD_OUT:                           ("Sold Out",                                    ItemClassification.filler),
    ItemKey.BUY_BLUE_FIRE:                      ("Buy Blue Fire",                               ItemClassification.progression),
    ItemKey.BUY_BOTTLE_BUG:                     ("Buy Bottle Bug",                              ItemClassification.progression),
    ItemKey.BUY_POE:                            ("Buy Poe",                                     ItemClassification.filler),
    ItemKey.BUY_FAIRYS_SPIRIT:                  ("Buy Fairy's Spirit",                          ItemClassification.progression),
    ItemKey.BUY_ARROWS_10:                      ("Buy Arrows (10)",                             ItemClassification.progression),
    ItemKey.BUY_BOMBS_20:                       ("Buy Bombs (20)",                              ItemClassification.progression),
    ItemKey.BUY_BOMBS_30:                       ("Buy Bombs (30)",                              ItemClassification.progression),
    ItemKey.BUY_BOMBS_535:                      ("Buy Bombs (5) [35]",                          ItemClassification.progression),
    ItemKey.BUY_RED_POTION_40:                  ("Buy Red Potion [40]",                         ItemClassification.filler),
    ItemKey.BUY_RED_POTION_50:                  ("Buy Red Potion [50]",                         ItemClassification.filler),

    # Enemy Souls
    ItemKey.SOUL_ITEM_POE:                      ("Poe Soul",                                    ItemClassification.progression),
    ItemKey.SOUL_ITEM_OCTOROK:                  ("Octorok Soul",                                ItemClassification.progression),
    ItemKey.SOUL_ITEM_KEESE:                    ("Keese Soul",                                  ItemClassification.progression),
    ItemKey.SOUL_ITEM_TEKTITE:                  ("Tektite Soul",                                ItemClassification.progression),
    ItemKey.SOUL_ITEM_LEEVER:                   ("Leever Soul",                                 ItemClassification.progression),
    ItemKey.SOUL_ITEM_PEAHAT:                   ("Peahat Soul",                                 ItemClassification.progression),
    ItemKey.SOUL_ITEM_LIZALFOS:                 ("Lizalfos and Dinolfos Soul",                  ItemClassification.progression),
    ItemKey.SOUL_ITEM_SHABOM:                   ("Shabom Soul",                                 ItemClassification.progression),
    ItemKey.SOUL_ITEM_BIRI_BARI:                ("Biri and Bari Soul",                          ItemClassification.progression),
    ItemKey.SOUL_ITEM_TAILPASARAN:              ("Tailpasaran Soul",                            ItemClassification.progression),
    ItemKey.SOUL_ITEM_SKULLTULA:                ("Skulltula Soul",                              ItemClassification.progression | ItemClassification.useful),
    ItemKey.SOUL_ITEM_TORCH_SLUG:               ("Torch Slug Soul",                             ItemClassification.progression),
    ItemKey.SOUL_ITEM_STINGER:                  ("Stinger Soul",                                ItemClassification.progression),
    ItemKey.SOUL_ITEM_MOBLIN:                   ("Moblin Soul",                                 ItemClassification.progression),
    ItemKey.SOUL_ITEM_ARMOS:                    ("Armos Soul",                                  ItemClassification.progression),
    ItemKey.SOUL_ITEM_DEKU_BABA:                ("Deku Baba Soul",                              ItemClassification.progression),
    ItemKey.SOUL_ITEM_BUBBLE:                   ("Bubble Soul",                                 ItemClassification.progression),
    ItemKey.SOUL_ITEM_FLYING_TRAP:              ("Flying Pot and Tile Soul",                    ItemClassification.progression),
    ItemKey.SOUL_ITEM_BEAMOS:                   ("Beamos Soul",                                 ItemClassification.progression),
    ItemKey.SOUL_ITEM_WALLMASTER:               ("Wallmaster and Floormaster Soul",             ItemClassification.progression),
    ItemKey.SOUL_ITEM_REDEAD_GIBDO:             ("ReDead and Gibdo Soul",                       ItemClassification.progression),
    ItemKey.SOUL_ITEM_SHELL_BLADE:              ("Shell Blade Soul",                            ItemClassification.progression),
    ItemKey.SOUL_ITEM_LIKE_LIKE:                ("Like Like Soul",                              ItemClassification.progression),
    ItemKey.SOUL_ITEM_TENTACLE:                 ("Parasitic Tentacle Soul",                     ItemClassification.progression),
    ItemKey.SOUL_ITEM_ANUBIS:                   ("Anubis Soul",                                 ItemClassification.progression),
    ItemKey.SOUL_ITEM_SPIKE:                    ("Spike Soul",                                  ItemClassification.progression),
    ItemKey.SOUL_ITEM_SKULL_KID:                ("Skull Kid Soul",                              ItemClassification.progression),
    ItemKey.SOUL_ITEM_FREEZARD:                 ("Freezard Soul",                               ItemClassification.progression),
    ItemKey.SOUL_ITEM_DEKU_SCRUB:               ("Deku Scrub Soul",                             ItemClassification.progression),
    ItemKey.SOUL_ITEM_WOLFOS:                   ("Wolfos Soul",                                 ItemClassification.progression),
    ItemKey.SOUL_ITEM_STALCHILD:                ("Stalchild Soul",                              ItemClassification.progression),
    ItemKey.SOUL_ITEM_GUAY:                     ("Guay Soul",                                   ItemClassification.progression),
    ItemKey.SOUL_ITEM_DOOR_MIMIC:               ("Door Mimic Soul",                             ItemClassification.progression),
    ItemKey.SOUL_ITEM_STALFOS:                  ("Stalfos Soul",                                ItemClassification.progression),
    ItemKey.SOUL_ITEM_DARK_LINK:                ("Dark Link Soul",                              ItemClassification.progression),
    ItemKey.SOUL_ITEM_FLARE_DANCER:             ("Flare Dancer Soul",                           ItemClassification.progression),
    ItemKey.SOUL_ITEM_DEAD_HAND:                ("Dead Hand Soul",                              ItemClassification.progression),
    ItemKey.SOUL_ITEM_GERUDO:                   ("Gerudo and Iron Knuckle Soul",                ItemClassification.progression),
    ItemKey.SOUL_ITEM_GOHMA:                    ("Gohma Soul",                                  ItemClassification.progression),
    ItemKey.SOUL_ITEM_DODONGO:                  ("Dodongo Soul",                                ItemClassification.progression),
    ItemKey.SOUL_ITEM_BARINADE:                 ("Barinade Soul",                               ItemClassification.progression),
    ItemKey.SOUL_ITEM_PHANTOM_GANON:            ("Phantom Ganon Soul",                          ItemClassification.progression),
    ItemKey.SOUL_ITEM_VOLVAGIA:                 ("Volvagia Soul",                               ItemClassification.progression),
    ItemKey.SOUL_ITEM_MORPHA:                   ("Morpha Soul",                                 ItemClassification.progression),
    ItemKey.SOUL_ITEM_BONGO_BONGO:              ("Bongo Bongo Soul",                            ItemClassification.progression),
    ItemKey.SOUL_ITEM_TWINROVA:                 ("Twinrova Soul",                               ItemClassification.progression),
    ItemKey.SOUL_ITEM_GANON:                    ("Ganon Soul",                                  ItemClassification.progression),

    # Ocarina Note Buttons
    ItemKey.OCA_BUTTON_ITEM_L:                  ("Ocarina L Button",                            ItemClassification.progression | ItemClassification.useful),
    ItemKey.OCA_BUTTON_ITEM_R:                  ("Ocarina R Button",                            ItemClassification.progression | ItemClassification.useful),
    ItemKey.OCA_BUTTON_ITEM_X:                  ("Ocarina X Button",                            ItemClassification.progression | ItemClassification.useful),
    ItemKey.OCA_BUTTON_ITEM_Y:                  ("Ocarina Y Button",                            ItemClassification.progression | ItemClassification.useful),
    ItemKey.OCA_BUTTON_ITEM_A:                  ("Ocarina A Button",                            ItemClassification.progression | ItemClassification.useful),

    ItemKey.UNBOTTLED_BIG_POE:                  ("Big Poe",                                     ItemClassification.progression),

    ItemKey.TRIFORCE_PIECE:                     ("Triforce Piece",                              ItemClassification.progression_skip_balancing),

    ItemKey.TRIFORCE:                           ("Triforce",                                    ItemClassification.progression)
}